### ISSUE TITLE
module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by ghost** [leimao/DeepLab_v3#10]
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from model import DeepLab
  File "C:\Users\DGRE\DeepLab-V3\model.py", line 6, in <module>
    from feature_extractor import MobileNet, Resnet, Vgg16
  File "C:\Users\DGRE\DeepLab-V3\feature_extractor.py", line 2, in <module>
    from nets import resnet_v2
  File "C:\Users\DGRE\DeepLab-V3\nets\resnet_v2.py", line 55, in <module>
    from nets import resnet_utils
  File "C:\Users\DGRE\DeepLab-V3\nets\resnet_utils.py", line 43, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by Vargha-Kh** [comment]
Use Tensorflow-gpu=1.15.0
requirement.txt will install tensorflow=2.4.0
